# Generated by Django 5.2 on 2025-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
